openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/crvillanu/VehicleMilesTraveled/1.0.0
info:
  description: | 
    API para registrar, consultar, actualizar y eliminar datos VMT,
    correspondientes al dataset VehicleMilesTraveled
  version: "1.0.0"
  title: CRUD sobre el dataset VehiclesMilesTraveled
paths:
  /VehicleMilesTraveled:
    post:
      summary: agrega un item al dataset
      operationId: addDataset
      description: Agrega un item al dataset
      responses:
        '201':
          description: item agregado
        '400':
          description: 'entrada inválida'
        '409':
          description: 'ya existe una entrada para ese condado y fecha'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntradaVMT'
        description: Item a agregar
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:110000390690:function:VehiclesMilesTraveled-CRUD/invocations"
        connectionType: "INTERNET"
    get:
      summary: obtener el dataset
      operationId: getDataset
      description: |
        Recupera la lista de entradas del dataset. 
        La lista es paginada automaticamente, en caso de no 
        retornar todos los resultados, se retorna un nextPageHint
        que permitirá recuperar la siguiente página en una llamada
        subsecuente.
      parameters:
        - in: query
          name: nextPageHint
          description: |
            llave para obtener la siguiente página a partir del
            último resultado de la página anterior
          schema:
            type: string
            format: json
      responses:
        '200':
          description: lista de entradas del dataset
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resultados'
        '400':
          description: parametro incorrecto
        '404':
          description: dataset vacío
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:110000390690:function:VehiclesMilesTraveled-CRUD/invocations"
        connectionType: "INTERNET"
  /VehicleMilesTraveled/{county_fips}/{date}:
    get:
      summary: obtener un item del dataset, si existe
      operationId: getDatasetItem
      description: |
        Recupera la lista de entradas del dataset. 
        La lista es paginada automaticamente, en caso de no 
        retornar todos los resultados, se retorna un nextPageHint
        que permitirá recuperar la siguiente página en una llamada
        subsecuente.
      parameters:
        - in: path
          name: county_fips
          required: true
          description: |
            FIPS del Condado
          schema:
            type: integer
            example: 1001
        - in: path
          name: date
          required: true
          description: |
            Fecha de la entrada
          schema:
            type: string
            format: date
            example: '2020-05-08'
      responses:
        '200':
          description: 'resultado de la busqueda en el dataset'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resultados'
        '400':
          description: 'parametro incorrecto'
        '404':
          description: 'no se encuentran el items en el dataset'
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:110000390690:function:VehiclesMilesTraveled-CRUD/invocations"
        connectionType: "INTERNET"
    put:
      summary: actualizar un item del dataset, si existe
      operationId: updateDatasetItem
      description: |
        Verifica si la entrada existe, y reemplaza por el objeto entregado.
      parameters:
        - in: path
          name: county_fips
          required: true
          description: |
            FIPS del Condado
          schema:
            type: integer
            example: 1001
        - in: path
          name: date
          required: true
          description: |
            Fecha de la entrada
          schema:
            type: string
            format: date
            example: '2020-05-08'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntradaVMT'
      responses:
        '200':
          description: 'item actualizado'
        '400':
          description: 'parametro incorrecto'
        '404':
          description: 'no se encuentran el item en el dataset'
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:110000390690:function:VehiclesMilesTraveled-CRUD/invocations"
        connectionType: "INTERNET"
    delete:
      summary: eliminar un item del dataset, si existe
      operationId: deleteDatasetItem
      description: |
        Verifica si la entrada existe, y elimina el item de la colección
      parameters:
        - in: path
          name: county_fips
          required: true
          description: |
            FIPS del Condado
          schema:
            type: integer
            example: 1001
        - in: path
          name: date
          required: true
          description: |
            Fecha de la entrada
          schema:
            type: string
            format: date
            example: '2020-05-08'
      responses:
        '200':
          description: 'item eliminado'
        '400':
          description: 'parametro incorrecto'
        '404':
          description: 'no se encuentran el item en el dataset'
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:110000390690:function:VehiclesMilesTraveled-CRUD/invocations"
        connectionType: "INTERNET"
  
components:
  schemas:
    Resultados:
      type: object
      properties:
        Items:
          type: array
          items:
            $ref: '#/components/schemas/EntradaVMT'
        Count:
          type: integer
          example: 7
        ScannedCount:
          type: integer
          example: 7
        LastEvaluatedKey:
          type: object
          format: json
    EntradaVMT:
      type: object
      required:
        - county_fips	
        - county_name	
        - state_name	
        - date	
        - county_vmt	
        - baseline_jan_vmt	
        - percent_change_from_jan	
        - mean7_county_vmt	
        - mean7_percent_change_from_jan	
        - date_at_low	
        - mean7_county_vmt_at_low	
        - percent_change_from_low
      properties:
        county_fips:
          type: integer
          example: 1001
        county_name:
          type: string
          minLength: 1
          example: 'Autauga'
        state_name:
          type: string
          minLength: 1
          example: 'Alabama'
        date:
          type: string
          format: date
          example: '2020-05-08'
        county_vmt:
          type: integer
          example: 3550000
        baseline_jan_vmt:
          type: integer
          example: 3550000
        percent_change_from_jan:
          type: number
          format: float
          example: -16.84
        mean7_county_vmt:
          type: number
          format: float
          example: 2724285.71
        mean7_percent_change_from_jan:
          type: number
          format: float
          example: -23.72
        date_at_low:
          type: string
          format: date
          example: '2020-12-04'
        mean7_county_vmt_at_low:
          type: number
          format: float
          example: 1542857.14
        percent_change_from_low:
          type: number
          format: float
          example: 80.83