AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  HTTP API para operaciones CRUD sobre coleccion DynamoDB tbVehiclesMilesTraveled
  
Globals:
  Function:
    Timeout: 10

Resources:
  VehiclesMilesTraveledApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionUri: api_definition.yaml
    DependsOn: VehiclesMilesTraveledCRUDfunction

  VehiclesMilesTraveledCRUDfunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: VehiclesMilesTraveled-CRUD
      Description: Procesar las operaciones CRUD sobre la tabla DynamoDB VehiclesMilesTraveledTable
      CodeUri: lambda-handler/
      Handler: app.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VehiclesMilesTraveledTable
      Events:
        CreateItem:
            Type: HttpApi
            Properties:
              ApiId: !Ref VehiclesMilesTraveledApi
              Path: /VehicleMilesTraveled
              Method: POST 
        GetAllItems:
          Type: HttpApi
          Properties:
            ApiId: !Ref VehiclesMilesTraveledApi
            Path: /VehicleMilesTraveled
            Method: GET
        GetAnItem:
          Type: HttpApi
          Properties:
            ApiId: !Ref VehiclesMilesTraveledApi
            Path: /VehicleMilesTraveled/{county_fips}/{date}
            Method: GET
        UpdateAnItem:
          Type: HttpApi
          Properties:
            ApiId: !Ref VehiclesMilesTraveledApi
            Path: /VehicleMilesTraveled/{county_fips}/{date}
            Method: PUT
        DeleteAnItem:
          Type: HttpApi
          Properties:
            ApiId: !Ref VehiclesMilesTraveledApi
            Path: /VehicleMilesTraveled/{county_fips}/{date}
            Method: DELETE

  VehiclesMilesTraveledTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: tbVehiclesMilesTraveled
      AttributeDefinitions:
        - AttributeName: county_fips
          AttributeType: N
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: county_fips
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      

Outputs:
  ApiEndpoint:
    Description: "URl Base de la API"
    Value: !Sub 
      - "https://${vApiId}.execute-api.${AWS::Region}.amazonaws.com"
      - { vApiId: !Ref VehiclesMilesTraveledApi }
  Function:
    Description: "DynamoDB handler function ARN"
    Value: !GetAtt VehiclesMilesTraveledCRUDfunction.Arn
